# frozen_string_literal: true

require "open3"
require "fileutils"
require "uri"

module Gemkeeper
  # Builds config.ru, spawns the rackup/puma process, and waits for HTTP readiness.
  class RackupProcess
    def initialize(config)
      @config = config
    end

    def start
      generate_config_ru
      Dir.chdir(@config.cache_dir) { launch_daemon }
      wait_for_server
    end

    def start_foreground
      generate_config_ru
      Dir.chdir(@config.cache_dir) do
        system(*build_rackup_cmd) || raise(ServerError, "rackup exited with status #{$CHILD_STATUS.exitstatus}")
      end
    end

    private

    def generate_config_ru
      FileUtils.mkdir_p(@config.cache_dir)
      FileUtils.mkdir_p(@config.gems_path)
      File.write(@config.config_ru_path, config_ru_content)
    end

    def config_ru_content
      gems_path = @config.gems_path
      cache_dir = @config.cache_dir
      <<~RUBY
        # frozen_string_literal: true
        # Auto-generated by Gemkeeper

        require "gemkeeper/compact_index_server"

        run Gemkeeper::CompactIndexServer.new(
          gems_path: #{gems_path.inspect},
          cache_dir: #{cache_dir.inspect}
        )
      RUBY
    end

    def build_rackup_cmd(*extra)
      [rackup_bin, "-I", lib_dir, @config.config_ru_path, "--host", "127.0.0.1",
       "-p", @config.port.to_s, "-s", "puma", *extra]
    end

    # The gem's own lib/, so the spawned rackup process can require gemkeeper
    # even when running from source (it does not inherit the exe's $LOAD_PATH).
    def lib_dir = File.expand_path("..", __dir__)

    def rackup_bin
      gem_home = ENV.fetch("GEM_HOME", nil)
      return "rackup" unless gem_home

      candidate = File.join(gem_home, "bin", "rackup")
      File.exist?(candidate) ? candidate : "rackup"
    end

    def launch_daemon
      _stdout, stderr, status = Open3.capture3(*build_rackup_cmd("-D", "-P", @config.pid_file))
      raise ServerError, "Failed to start server:\n#{stderr}" unless status.success? || File.exist?(@config.pid_file)
    end

    def wait_for_server
      ServerReadinessProbe.new(@config.server_url).wait
    end
  end
end
