# frozen_string_literal: true

require "open3"
require "fileutils"
require "uri"

module Gemkeeper
  # Builds config.ru, spawns the rackup/puma process, and waits for HTTP readiness.
  class RackupProcess
    def initialize(config)
      @config = config
    end

    def start
      generate_config_ru
      Dir.chdir(@config.cache_dir) { launch_daemon }
      wait_for_server
    end

    def start_foreground
      generate_config_ru
      Dir.chdir(@config.cache_dir) { system(*build_rackup_cmd) }
    end

    private

    def generate_config_ru
      FileUtils.mkdir_p(@config.cache_dir)
      FileUtils.mkdir_p(@config.gems_path)
      File.write(@config.config_ru_path, config_ru_content)
    end

    def config_ru_content
      gems_path = @config.gems_path
      <<~RUBY
        # frozen_string_literal: true
        # Auto-generated by Gemkeeper

        require "geminabox"

        Geminabox.data = #{gems_path.inspect}
        Geminabox.rubygems_proxy = true

        run Geminabox::Server
      RUBY
    end

    def build_rackup_cmd(*extra)
      [rackup_bin, @config.config_ru_path, "--host", "127.0.0.1",
       "-p", @config.port.to_s, "-s", "puma", *extra]
    end

    def rackup_bin
      gem_home = ENV.fetch("GEM_HOME", nil)
      return "rackup" unless gem_home

      candidate = File.join(gem_home, "bin", "rackup")
      File.exist?(candidate) ? candidate : "rackup"
    end

    def launch_daemon
      _stdout, stderr, status = Open3.capture3(*build_rackup_cmd("-D", "-P", @config.pid_file))
      raise ServerError, "Failed to start server:\n#{stderr}" unless status.success? || File.exist?(@config.pid_file)
    end

    def wait_for_server
      ServerReadinessProbe.new(@config.geminabox_url).wait
    end
  end
end
