# frozen_string_literal: true

require "open3"
require "fileutils"

module Gemkeeper
  # Owns the rackup/puma lifecycle so CLI commands delegate process management here.
  class ServerManager
    attr_reader :config

    def initialize(config)
      @config = config
    end

    def start
      ensure_not_running!
      generate_config_ru
      start_server
    end

    def start_foreground
      ensure_not_running!
      generate_config_ru
      start_server_foreground
    end

    def stop
      raise ServerNotRunningError, "Server is not running" unless running?

      pid = read_pid
      Process.kill("TERM", pid)
      wait_for_process_exit(pid)
      cleanup_pid_file
      true
    rescue Errno::ESRCH
      cleanup_pid_file
      true
    end

    def status
      if running?
        { running: true, pid: read_pid, url: config.geminabox_url }
      else
        { running: false }
      end
    end

    def running?
      return false unless File.exist?(config.pid_file)

      pid = read_pid
      return false unless pid

      process_alive?(pid)
    end

    private

    def ensure_not_running!
      raise ServerAlreadyRunningError, "Server is already running (PID: #{read_pid})" if running?
    end

    def generate_config_ru
      gems_path = config.gems_path
      FileUtils.mkdir_p(config.cache_dir)
      FileUtils.mkdir_p(gems_path)

      content = <<~RUBY
        # frozen_string_literal: true
        # Auto-generated by Gemkeeper

        require "rubygems/indexer"
        require "geminabox"

        Geminabox.data = #{gems_path.inspect}
        Geminabox.rubygems_proxy = true

        run Geminabox::Server
      RUBY

      File.write(config.config_ru_path, content)
    end

    def build_rackup_cmd(*extra)
      ["rackup", config.config_ru_path, "--host", "127.0.0.1", "-p", config.port.to_s, "-s", "puma", *extra]
    end

    def build_start_cmd
      build_rackup_cmd("-D", "-P", config.pid_file)
    end

    def build_foreground_cmd
      build_rackup_cmd
    end

    def start_server
      cmd = build_start_cmd

      Dir.chdir(config.cache_dir) do
        _stdout, stderr, status = Open3.capture3(*cmd)

        raise ServerError, "Failed to start server:\n#{stderr}" unless status.success? || File.exist?(config.pid_file)
      end

      # Wait for server to be ready
      wait_for_server
    end

    def start_server_foreground
      Dir.chdir(config.cache_dir) do
        system(*build_foreground_cmd)
      end
    end

    def wait_for_process_exit(pid)
      10.times do
        return unless process_alive?(pid)

        sleep 0.5
      end
      Process.kill("KILL", pid) if process_alive?(pid)
    end

    def wait_for_server(timeout: 10)
      require "net/http"

      uri = URI(config.geminabox_url)
      (timeout / 0.5).ceil.times do
        return true if server_responding?(uri)

        sleep 0.5
      end

      raise ServerError, "Server failed to start within #{timeout} seconds"
    end

    def server_responding?(uri)
      response = Net::HTTP.get_response(uri)
      response.is_a?(Net::HTTPSuccess) || response.is_a?(Net::HTTPRedirection)
    rescue Errno::ECONNREFUSED, Errno::ECONNRESET, SocketError
      false
    end

    def read_pid
      pid_file = config.pid_file
      return nil unless File.exist?(pid_file)

      pid = File.read(pid_file).strip.to_i
      pid.positive? ? pid : nil
    end

    def process_alive?(pid)
      Process.kill(0, pid)
      true
    rescue Errno::ESRCH, Errno::EPERM
      false
    end

    def cleanup_pid_file
      FileUtils.rm_f(config.pid_file)
    end
  end
end
