#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "gemkeeper"
require "gemkeeper/cli"

begin
  Dry::CLI.new(Gemkeeper::CLI).call
rescue SystemExit => e
  exit ARGV.include?("--help") || ARGV.include?("-h") ? 0 : e.status
end
